doctrine:
    dbal:
        default_connection: core
        connections:
            core:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '16.0'
                driver: 'pdo_pgsql'

    orm:
        default_entity_manager: core
        enable_native_lazy_objects: true

        entity_managers:
            core:
                connection: core
                mappings:
                    User:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\User\Domain'
                        alias: User

                    Access:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Access/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Access\Domain'
                        alias: Access
