services:
    api.access.list_provider:
        class: App\Access\Infrastructure\UI\List\ListProvider
        arguments:
            $queryBus: '@query.bus'
            $loggedUserProvider: '@service.user.authenticated_user_provider'
        tags:
            - { name: api_platform.state_provider }
