imports:
    - { resource: services/api/*.yaml }
    - { resource: services/command_handlers/*.yaml }
    - { resource: services/console/*.yaml }
    - { resource: services/event_handlers/*.yaml }
    - { resource: services/query_handlers/*.yaml }
    - { resource: services/repositories/*.yaml }
    - { resource: services/security/*.yaml }
    - { resource: services/services/*.yaml }
    - { resource: services/subscribers/*.yaml }
    - { resource: services/updaters/*.yaml }

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    Predis\ClientInterface:
        class: Predis\Client
        arguments:
            - '%env(REDIS_URL)%'
