parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $eventsBus: '@events.bus'
            #$commandsBus: '@commands.bus'
            $queryBus: '@query.bus'

    App\:
        resource: '../src/'

    App\Shared\Infrastructure\Http\ApiExceptionSubscriber:
        arguments:
            $errorsLogger: '@monolog.logger.errors'

    App\Shared\Application\Service\Encryptor:
        arguments: ['%env(base64:ENCRYPT_KEY)%']

    App\User\Application\Port\AccessProvisioner:
        alias: App\Shared\Infrastructure\Bridge\UserAccess\MessengerAccessProvisioner

    Predis\ClientInterface:
        class: Predis\Client
        arguments:
            - '%env(REDIS_URL)%'

    App\Shared\Infrastructure\Persistence\ElasticSearch\Command\CreateElasticsearchIndicesCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\User\Application\Command\UpdateCommandHandler:
        arguments:
            $updaters: !tagged_iterator app.user_updater

    App\User\Application\Command\Updater\:
        resource: '../src/User/Application/Command/Updater/'
        exclude:
            - '../src/User/Application/Command/Updater/UserFieldUpdater.php'
        tags: ['app.user_updater']
