services:
    event.user.update_projection_on_user_created:
        class: App\User\Application\Event\UpdateUserProjectionOnUserCreatedEventHandler
        arguments:
            $commandBus: '@commands.bus'
        tags:
            - { name: messenger.message_handler, bus: events.bus }

    event.user.update_projection_on_user_updated:
        class: App\User\Application\Event\UpdateUserProjectionOnUserUpdatedEventHandler
        arguments:
            $commandBus: '@commands.bus'
        tags:
            - { name: messenger.message_handler, bus: events.bus }

    event.user.update_projection_on_user_deleted:
        class: App\User\Application\Event\UpdateUserProjectionOnUserDeletedEventHandler
        arguments:
            $commandBus: '@commands.bus'
        tags:
            - { name: messenger.message_handler, bus: events.bus }

    event.user.send_welcome_email_on_user_created:
        class: App\User\Application\Event\SendWelcomeEmailToUserOnUserCreatedEventHandler
        arguments:
            $commandBus: '@commands.bus'
        tags:
            - { name: messenger.message_handler, bus: events.bus }
