App\Access\Domain\Group:
    operations:
        ApiPlatform\Metadata\GetCollection:
            uriTemplate: /v1/groups
            status: 200
            input: false
            output: App\Access\UI\List\Response\GroupItemResponse
            provider: api.access.list_provider
            read: true
            deserialize: false
            validate: false
            paginationEnabled: true
