App\User\Domain\User:
    operations:
        ApiPlatform\Metadata\Post:
            uriTemplate: /v1/user
            status: 201
            input: App\User\Infrastructure\UI\Create\Request\CreateRequest
            output: false
            processor: api.user.create_processor
            read: false
            deserialize: true
            validate: true

        ApiPlatform\Metadata\Put:
            uriTemplate: /v1/user/{id}
            status: 202
            input: App\User\Infrastructure\UI\Update\Request\UpdateRequest
            output: false
            processor: api.user.update_processor
            read: false
            deserialize: true
            validate: true
            requirements:
                id: '^[0-9a-fA-F-]{36}$'

        ApiPlatform\Metadata\Delete:
            uriTemplate: /v1/user/{id}
            status: 202
            input: false
            output: false
            processor: api.user.delete_processor
            read: false
            deserialize: false
            validate: false
            requirements:
                id: '^[0-9a-fA-F-]{36}$'

        ApiPlatform\Metadata\GetCollection:
            uriTemplate: /v1/users
            status: 200
            input: false
            output: App\User\Infrastructure\UI\List\Response\UserItemResponse
            provider: api.user.list_provider
            read: true
            deserialize: false
            validate: false
            paginationEnabled: true
